version: '2'
services:
  logstash:
    image: logstash
    command: bash -c "STREAM=<the name of your table in atom cluster> logstash --allow-env -f /etc/logstash/conf.d/logstash.conf"
    volumes: 
    - ${ENV}/logstash_dock.conf:/etc/logstash/conf.d/logstash.conf
    - ${ENV}/file.txt:/etc/logstash/file.txt
    container_name: logstash-atom