version: '2'
services:
  logstash:
    image: logstash:2.3
    command: bash -c "logstash --allow-env -f /etc/logstash/conf.d/logstash.conf"
    environment:
     STREAM: ${STREAM}
    volumes: 
    - <absolute path to your log stash.conf file on your server>:/etc/logstash/conf.d/logstash.conf
    - <absolute path to file with your input data>:/etc/logstash/file.txt
    container_name: logstash-atom
volumes:
   atom: {}